#ifndef CRETE_CUSTOM_OPCODE_H
#define CRETE_CUSTOM_OPCODE_H

#define CRETE_INSTR_GENERATE(x, y)            \
    ".byte 0x0F, 0x3F\n"                      \
    ".byte 0x00, 0x" #x ", 0x" #y ", 0x00\n"  \
    ".byte 0x00, 0x00, 0x00, 0x00\n"

// For crete-run/preload-run
#define CRETE_INSTR_PRIME_VALUE 0x020000
#define CRETE_INSTR_PRIME() CRETE_INSTR_GENERATE(00, 02)

#define CRETE_INSTR_SEND_TARGET_PID_VALUE 0x030000
#define CRETE_INSTR_SEND_TARGET_PID() CRETE_INSTR_GENERATE(00, 03)

#define CRETE_INSTR_VOID_TARGET_PID_VALUE 0x040000
#define CRETE_INSTR_VOID_TARGET_PID() CRETE_INSTR_GENERATE(00, 04)

#define CRETE_INSTR_DUMP_VALUE 0x050000
#define CRETE_INSTR_DUMP() CRETE_INSTR_GENERATE(00, 05)

// For program under test
#define CRETE_INSTR_MAKE_CONCOLIC_INTERNAL_VALUE 0x060000
#define CRETE_INSTR_MAKE_CONCOLIC_INTERNAL() CRETE_INSTR_GENERATE(00, 06)
#define CRETE_INSTR_PRE_MAKE_CONCOLIC_VALUE 0x070000
#define CRETE_INSTR_PRE_MAKE_CONCOLIC() CRETE_INSTR_GENERATE(00, 07)
#define CRETE_INSTR_SEND_CONCOLIC_NAME_VALUE 0x080000
#define CRETE_INSTR_SEND_CONCOLIC_NAME() CRETE_INSTR_GENERATE(00, 08)

#define CRETE_INSTR_CHECK_TARGET_PID_VALUE 0x0E0000
#define CRETE_INSTR_CHECK_TARGET_PID() CRETE_INSTR_GENERATE(00, 0E)


#define CRETE_INSTR_WAIT_TEST_CASE_VALUE 0x0F0000
#define CRETE_INSTR_WAIT_TEST_CASE() CRETE_INSTR_GENERATE(00, 0F)

#endif // CRETE_CUSTOM_OPCODE_H
